---
title: "R Notebook"
output: html_notebook
---

1) Thème: COVID-19 et profil des pays.

2) Question: Quel est le profil des pays les plus frappés par la COVID-19?

3) Questions secondaires :
i) Y-aurait-il un lien entre le taux de cas de COVID-19 et le niveau de développement économique des pays?
ii) Y-aurait-il un lien entre le taux de cas de COVID-19 et la prévalence de maladies pulmonaires ?
iii) Y-aurait-il un lien entre la COVID-19 et le ratio du nombre de touristes et la population ?

4) Graphiques et statistiques :
i) Nuage de points comparant la prévalence de la COVID-19 en 2020 avec le PIB par habitant en 2018.
ii) Nuage de points comparant la prévalence de la COVID-19 en 2020 avec la prévalence de maladies pulmonaires en 2018.
iii) Nuage de points comparant la prévalence de la COVID-19 en 2020 avec le taux de touristes en 2018.
iv) Tableau interactif présentant le profil, par pays et par continent, suivant la sélection de l'utilisateur du dashboard. Le tableau indique la prévalence de la COVID-19, celle d'au moins une maladie pulmonaire (à préciser), le PIB par habitant en 2019 et en 2020, un indicateur relatif au climat (plus faible et plus élevée température).
iv) Des cartes thématiques du monde, indiquant la prévalence de la COVID-19 et d'autres indicateurs, avec la possibilité d'avtla carte par région du monde, suivant le choix de l'utilisateur du dashboard.

5) Liste des variables et les sources des données:

```{r}
Variables<-c("Cas de COVID", "PIB par habitant","Population","Nombre de tests","IDH")
```
